### ISSUE TITLE
How to test exercises that expect an error or exception?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/chapel#15]
The nucleotide exercise has one test that asserts that an error occurs. What would a test like that look like in Chapel?

Here's what the default test would look like:

```
proc testSomething(test : borrowed Test) throws {
  test.assertEqual(nucleotideCounts("GGGGGGG"), {"A"=>0, "C"=>0, "G"=>7, "T"=>0});
}
```

`A`, `C`, `G`, and `T` are considered valid nucleotides, and the test for the error case passes in a strand of `AGXXACT`.

The problem specification says `{"error"=>"Invalid nucleotide in strand"}`. Some tracks specify the exact error text as part of the test, others test only for the right type of error, leaving the text up to the individual.

**Comment by lucaferranti** [comment]
I think `UnitTest` does not have an `assertThrows` function. Off the top of my head, I would do the following

```chapel
use UnitTest;
use UnitTest.TestError; // needed to define the custom AssertionError

proc fun(x : int) throws {
  if x > 0 then throw new IllegalArgumentError("invalid input");
  else return 3;
}


proc testFun(test : borrowed Test) throws {
  try {
    fun(3); // replace this with function-under-test and input(s)
    throw new owned AssertionError("function was expected to throw an error");
  } catch e: IllegalArgumentError {
    test.assertEqual(e.message(), "invalid input"); // replace this with expected error message
  }
}

UnitTest.main();
```

maybe let's wait 1-2 days with this to see if I can think of a better solution

**Comment by kytrinyx** [comment]
Cool. Yeah, that would totally work, but I'll just defer this exercise (and any others that have errors) until you've had a chance to ponder it for a bit.

**Comment by kytrinyx** [comment]
Have you had a chance to think about how you'd like to test for the error cases?

If not, let's just go with what you have above.

**Comment by lucaferranti** [comment]
I checked with others on the Chapel forum and indeed a work-around like that is necessary and mine above should be good.

Before giving the final green light to the template above, I want to quickly check how it behaves if other exceptions (e.g. interruptions) occur. Probably it just needs an extra `catch` branch to rethrow exceptions. I'll post the updated template tomorrow morning at latest

**Comment by kytrinyx** [comment]
That sounds great. Thanks for checking!

**Comment by lucaferranti** [comment]
did some tweaking and we have a winner (at least for now). I tested it by trying to impelment the collatz-conjecture (because it had few tests 😅 ) the template should be (leaving out the usual things)

```chapel
use UnitTest;
use UnitTest.TestError; // needed to define the custom AssertionError

proc testCaseUnderTest(test : borrowed Test) throws {
  try {
    steps(0); // Placeholder for function call here
    throw new AssertionError("Function was expected to throw an error");
  } catch e : IllegalArgumentError {
    test.assertEqual(e.message(), "Expected message here"); // placeholder for expected error message here
  } catch e {
    throw e;
  }
}
```

see #40 for seeing it in action

**Comment by kytrinyx** [comment]
Niiiiice! I will whip up some templates for the other exercises in #19 that have error handling.

**Comment by kytrinyx** [comment]
@lucaferranti Is there a material difference between

```
throw new owned AssertionError("function was expected to throw an error");
```
vs
```
throw new AssertionError("function was expected to throw an error");
```

In this issue it says 'owned' but in the code that we ended up with there's no `owned`.

**Comment by lucaferranti** [comment]
@kytrinyx sorry for the delay. They are the same. `owned` is the default memory management mechanism

**Comment by kytrinyx** [comment]
Excellent, thank you!
