### ISSUE TITLE
Add initial exercises

### ISSUE THREAD

**Issue by lucaferranti** [exercism/chapel#19]
from exercism docs [initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises):

- [x] hello-world #4 
- [x] leap #17 
- [x] gigasecond #32 (dates)
- [x] isogram #12 
- [x] resistor-color #14 
- [x] nucleotide-count #41 
- [x] collatz-conjecture #40
- [x] darts #26 
- [x] two-fer #8 
- [x] high-scores #28 
- [x] raindrops #24 
- [x] bob #27 
- [x] allergies #25 
- [x] series #44 
- [x] circular-buffer #51 
- [x] meetup #50 
- [x] yacht #34 
- [x] dominoes #35 
- [x] diamond #36 
- [ ] alphametics #37 
- [ ] forth #54

**Comment by lucaferranti** [comment]
the hello-world issue  #3 had the template

```
{
  "slug": "hello-world",
  "name": "Hello World",
  "uuid": "",
  "practices": [],
  "prerequisites": [],
  "difficulty": 1,
  "topics": []
}
 ```
 
 what's the topics field for? I couldn't find it in the exercism docs.
 
 Also, should the `practices` field be left empty since the track does not have concepts yet?

**Comment by kytrinyx** [comment]
Yes, for `hello-world` practices and prerequisites are required to be empty.

I think for `practices` we can leave them empty until we have concepts, and then populate this field as we build out the syllabus.

I can't find the documentation for topics. I copied these fields from the config.json of a live track, but I think that track simply hasn't cleaned up, and these are left over from a previous version of Exercism. I will submit a PR (here and in the other track) to delete the topics.

**Comment by kytrinyx** [comment]
Actually, it looks like most of the tracks has this topics field. I will double-check with the team to see if I should remove it everywhere.

**Comment by kytrinyx** [comment]
Okay, clarified: it's deprecated. Some tracks have data in it, and will keep it around for their own sake until they implement concepts, at which point they'll remove it. I will submit a PR here to remove them from this track, since we don't need them.

**Comment by iHiD** [comment]
> I think for practices we can leave them empty until we have concepts, and then populate this field as we build out the syllabus.

I agree with this. For exercises generated from problem-specs (e.g. all the ones above), I'd generally recommend "copying" the `practices` from another track at the time that the syllabus is ready to go live (ie it has 10+ concepts), and then removing/rewording/replacing any concepts that aren't relevant to this track. That has been the least-path-of-resistence for most tracks doing this.

**Comment by lucaferranti** [comment]
The [add initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises)  page on the docs has a table with 20 exercises and recommended difficulty and concepts. For start, I was thinking to follow that.

**Comment by lucaferranti** [comment]
:rotating_light: :rotating_light: :rotating_light: 

**We have 20 exercises!** 

:tada: :tada: :tada: :tada: :
