### ISSUE TITLE
Should we implement skipping?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/chapel#22]
In #12 we started discussing whether or not we should implement some way of incrementally enabling tests as people solve an exercise. This helps guide people to thinking about just the next useful step rather than overwhelming them with _all_ the failures all at once.

@lucaferranti said:
> I think this could be implemented using Chapel `skipIf` and `dependsOn`. I can try drafting a quick prototype.

And also asked a great question about how this works in the online editor. (@ErikSchierboom -- do you know what we currently do for other tracks?)

**Comment by lucaferranti** [comment]
using `dependsOn` a test is skipped if the test it depends on fails or is skipped. However, it still prints the tests are skipped, e.g.

```
======================================================================
FAIL tests.chpl: testColorCodesBlack()
----------------------------------------------------------------------
AssertionError: assert failed - '0' != '1'

======================================================================
SKIPPED tests.chpl: testColorCodesWhite()
----------------------------------------------------------------------
testColorCodesWhite() skipped because testColorCodesBlack() failed

======================================================================
SKIPPED tests.chpl: testColorCodesOrange()
----------------------------------------------------------------------
testColorCodesOrange() skipped because testColorCodesWhite() Skipped

======================================================================
SKIPPED tests.chpl: testColors()
----------------------------------------------------------------------
testColors() skipped because testColorCodesOrange() Skipped

----------------------------------------------------------------------
Ran 1 test in 18.9851 seconds

FAILED (failures = 1 skipped = 3 )
```

feels like a lot of visual noise, doesn't it? Not sure it's better than just running all tests?

**Comment by kytrinyx** [comment]
Yeah, it feels like maybe it's not ideal.

Let's just not do anything about skipping or whatever for now, and then re-evaluate what we can do to make the experience a bit nicer later.

**Comment by iHiD** [comment]
FYI, if you do allow skipping, the test-runner must unskip all the tests before it runs. The online editor then shows the first failing test (in order from first to last in the resulting config.json file).

**Comment by ErikSchierboom** [comment]
Yes, as @iHiD said, the test runner unskips the tests before it runs.

**Comment by kytrinyx** [comment]
I'm going to close this since it's not actionable for now.
