### ISSUE TITLE
Protected branch settings on this repository

### ISSUE THREAD

**Issue by kytrinyx** [exercism/chapel#29]
I updated the settings as follows (everything below it did not get a checkbox).

I couldn't find a setting to enforce squash-and-merge; do you know if that exists and if so what it is called?

<img width="785" alt="Screen Shot 2022-10-10 at 9 07 03 AM" src="https://user-images.githubusercontent.com/276834/194813945-9ae13860-8800-4643-aea0-4dad8cb79551.png">

**Comment by lucaferranti** [comment]
Ah, maybe I misremember there was a setting for that? Let me check on other repos where I'm owner

**Comment by lucaferranti** [comment]
on the settings on-page scrolling down to Pull Requests I find
![image](https://user-images.githubusercontent.com/49938764/194815522-3232f1ff-0cfa-4127-b917-d2a60e34b1fc.png)

I think disabling the first and last would do what we want?

**Comment by kytrinyx** [comment]
Oh, right. I was thinking this had to do with protected branches, but it's actually default behavior. One sec.

**Comment by kytrinyx** [comment]
I changed it to this:

<img width="806" alt="Screen Shot 2022-10-10 at 9 29 20 AM" src="https://user-images.githubusercontent.com/276834/194816847-fcbbf0e3-e160-44bc-9978-cd9f676e7ba4.png">

**Comment by lucaferranti** [comment]
I actually happen to have a trivial PR updating one link, we can use it to test this

**Comment by lucaferranti** [comment]
https://github.com/exercism/chapel/pull/30 for verifying settings work

**Comment by lucaferranti** [comment]
![image](https://user-images.githubusercontent.com/49938764/194819281-6281cd04-44ac-4b2c-8be5-f6a3530c1b19.png)

🎉

**Comment by kytrinyx** [comment]
Excellent. Thanks for testing that!
