### ISSUE TITLE
Implement Hello World exercise

### ISSUE THREAD

**Issue by kytrinyx** [exercism/chapel#3]
I've added some notes for you to follow once you're ready to implement the first exercise (https://exercism.org/docs/building/tracks/new/add-first-exercise)

If these notes work and are helpful, let me know and I'll update the official documentation with them. If not please holler so we can figure out what's missing!

You can get the basics for the exercise in place by doing the following:

```
bin/fetch-configlet
```

Then you'll need to add some bits and pieces to the config.json in the "exercises.practice" array
```

      {
        "slug": "hello-world",
        "name": "Hello World",
        "uuid": "",
        "practices": [],
        "prerequisites": [],
        "difficulty": 1,
        "topics": []
      }
```

And then add the output from the following command to the uuid field for hello-world:

```
bin/configlet uuid
```

Then run the sync command:

```
bin/configlet sync --update --docs --metadata --tests
```

Next, add your GitHub username to "authors" in `exercises/practice/hello-world/.meta/config.json` (no "@" or anything).

Next you'll need to create the following in the `exercise/practice/hello-world` directory:
- a test suite with a single test ("the tests")
- a full solution with the text "Goodbye, Mars!" instead of the text "Hello, World!", causing the test to fail. ("the stub")
- a full, correct solution ("the example solution")

To do so you'll have to decide what the file paths are going to look like for the exercise. Ideally, you'll have filenames and paths that are idiomatic for the language. That said, if there's not a fairly strict requirement/expectation, prefer a shallower file structure (maybe even no subdirectories).

The example solution will go in the `.meta/` directory of the exercise, and you can name it anything. `example` is a common choice for the basename.

Once you have created the files you'll need to update the `exercises/practice/hello-world/.meta/config.json` file to have those paths.

**Comment by lucaferranti** [comment]
thank you very much! I'm hoping to get started with this already this evening.

Looking forward to work on this
