### ISSUE TITLE
bin/test - store original terminal at start of script and change back at exit

### ISSUE THREAD

**Issue by kytrinyx** [exercism/chapel#39]
Do you happen to know off the top of your head how to grab the current terminal color?

Right now running the script changes the color of any following commands to either red or green (depending on whether the tests passed or failed).

**Comment by lucaferranti** [comment]
really? I cannot reproduce this on my terminal, but sounds very strange. What OS shell are you using?

I think the way I handle the colors is faulty, or at least only working for specific situations. For example, in the gh actions log it doesn't show any colors at all

**Comment by kytrinyx** [comment]
Oh, weird! I'm using `bash` on Mac OS. It's totally not a big deal, I can just `reset` and it's all good. Maybe some day I'll be motivated to figure out why it is happening or how to avoid it :)

**Comment by kytrinyx** [comment]
I'm going to close this since it's not actionable for now.

**Comment by lucaferranti** [comment]
we could also remove the colors and keep a low priority enhancement issue to reinsert those

**Comment by kytrinyx** [comment]
Eh. Either way :) I think it's fine the way it is. Let's leave it.
