### ISSUE TITLE
Series: what would a sample test look like?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/chapel#42]
Here is a sample entry in the canonical data for the `series` problem.

```
{
  "uuid": "19bbea47-c987-4e11-a7d1-e103442adf86",
  "description": "slices of two overlap",
  "property": "slices",
  "input": {
    "series": "9142",
    "sliceLength": 2
  },
  "expected": [
    "91",
    "14",
    "42"
  ]
}
```

In Ruby the test looks like this:

```
  def test_slices_of_two_overlap
    series = Series.new("9142")
    assert_equal ["91", "14", "42"], series.slices(2)
  end
```

What would the test look like in Chapel?

If I have an idea what it needs to look like I can generate the exercise stub.

**Comment by lucaferranti** [comment]
If I properly inferred the goal of the exercise from the example, one needs to create a class series and define some methods on it?

in that case, the test function body would look like

```chapel
var series = new Series("9142");
test.assertEqual(series.slices(2), ["91, "14", "42"]);
```

**Comment by lucaferranti** [comment]
ah no wait, one needs not create a class?

could be just

```chapel
test.assertEqual(slices("9142", 2), ["91, "14", "42"]);
```

**Comment by kytrinyx** [comment]
Yeah there's no need for a class. Classes are idiomatic in Ruby, so that's a language-specific choice.

**Comment by lucaferranti** [comment]
closing since PR implementing series is merged
