### ISSUE TITLE
exercises instruction

### ISSUE THREAD

**Issue by lucaferranti** [exercism/chapel#45]
currently the exercises stub only have the module definition

```chapel
module MyExercise {
  // write your solution here
}
```

and students would have to go reverse engineer the tests to figure out what exactly to implement. This is fine for more advanced users/exercises, but for beginners it can constitute a pointless extra cognitive load.

A few options:

- add the function definition to the template, e.g. 
```chapel
proc myFunction(a: int, b:string) {
  // write your code here
}
```
this would be fine for the very first exercises as it also shows students how to define a function in chapel.

- Have an `instructions.append.md` file in each exercise saying what functions should be implemented (or write this directly in `instructions.md`, but maybe better not to change that if it's automatically generated.

I would maybe lean towards the second option. Comments, suggestions how this is dealt with in other tracks?

**Comment by kytrinyx** [comment]
Tracks have done all of the above, including just letting students fend for themselves.

Maybe for the first batch of 20 exercises we could do the following:
- add the function definition for exercises with difficulty=1
- add `instructions.append.md` for exercises with difficulty=2
- let students fend for themselves (looking at error messages and inspecting the tests) for exercises with difficulty=3

?

That would give us some experience with each approach, and when we add more exercises we might have more of a sense of what the right choice is.
