### ISSUE TITLE
revisit difficulty levels

### ISSUE THREAD

**Issue by lucaferranti** [exercism/chapel#46]
So far I assumed there were only 3 difficulty levels (1=easy, 2=medium, 3=hard), but now I see in the exercism docs the levels actually go from 1 to 10 (1-3 easy, 4-7 medium, 8 - 10 hard).

Is the difficulty level for each exercise standardized somewhere or can each track decide those freely? If so, is there much variation between languages or where do other take inspiration to decide the difficulty level?

**Comment by kytrinyx** [comment]
It's not standardized. Some exercises end up being trivial in some languages and hard in others.

To start out we really just guess based on... well, gut feeling, mostly. Later we'll see what trips people up, or where people drop off, and we can adjust difficulty levels.

**Comment by lucaferranti** [comment]
yes, this sounds good.

My gut feeling tells me 2 for an intermediate exercise and 3 for a hard one is too little. I'll open shortly a PR updating the difficulty levels to reflect the exercism documentation

**Comment by kytrinyx** [comment]
That makes sense and sounds like a good approach.
