### ISSUE TITLE
fix syntax highlight

### ISSUE THREAD

**Issue by lucaferranti** [exercism/chapel#52]
I was looking at the track [homepage](https://exercism.org/tracks/chapel) (atm only visible to maintainers at the moment) and I noticed a couple of issues

- the logo is not displayed (which I guess it's understandable, since I dont remeber loading it anywhere)
![image](https://user-images.githubusercontent.com/49938764/198212684-b3a13547-aec6-4e7d-aa28-2417094b2d8e.png)

- the code snippet does not have syntax highlights (chapel should be supported from highlights.js)

![image](https://user-images.githubusercontent.com/49938764/198212852-8da9263a-d2ce-4cc9-b86e-b15b2d9f7e7d.png)

any pointers on how to debug / fix this are very welcome

**Comment by kytrinyx** [comment]
There's a step in the [new track checklist](https://exercism.org/docs/building/tracks/new) called [Prepare for launch](https://exercism.org/docs/building/tracks/new/prepare-for-launch). The first item there is to request a track icon. Once that's done, the logo will show up on the track about page.

I'm not sure about the snippet. The value is set correctly in the `config.json` from what I can tell (https://github.com/exercism/chapel/blob/main/config.json#L16).

I submitted Hello, World, and there's no syntax highlighting on the code there, either.

<img width="511" alt="Screen Shot 2022-10-27 at 10 50 32 AM" src="https://user-images.githubusercontent.com/276834/198238809-7cd8586b-aefc-4662-a34d-57e229990418.png">

@ErikSchierboom do you know if there's an extra step to get the highlighting working?

**Comment by lucaferranti** [comment]
mmm, I don't see chapel in highlightjs demo: https://highlightjs.org/static/demo/

but it is listed in the list of supported languages: https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md

when I used it in a web page a few years ago, I vaguely remember that I had to choose what languages to download, maybe the website needs to reinstall it with chapel included? Don't know, just a wild guess

**Comment by kytrinyx** [comment]
That's a good guess, @lucaferranti. We'll try that, unless @ErikSchierboom knows something different!

**Comment by ErikSchierboom** [comment]
> but it is listed in the list of supported languages: https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md

Well yes, but only via a plugin: [highlightjs-chapel](https://github.com/chapel-lang/highlightjs-chapel)
Looking at that page, it doesn't seem to have an NPM package (confirmed by https://www.npmjs.com/search?q=chapel). 
We need that in order to have the syntax highlighting work on the website, so either we:

- Get the people writing that plugin to publish to NPM
- Fork and publish yourselves

**Comment by kytrinyx** [comment]
> Get the people writing that plugin to publish to NPM

That would be ideal. @lucaferranti Would you see if you're able to get in touch with them?

**Comment by lucaferranti** [comment]
> Would you see if you're able to get in touch with them?

yes, I will do that.

**Comment by lucaferranti** [comment]
fwi, the syntax highlight plugin should get registered soon https://github.com/chapel-lang/highlightjs-chapel/pull/11

**Comment by lucaferranti** [comment]
@ErikSchierboom the highlightjs-chapel repo is now registered as npm plugin: https://www.npmjs.com/package/highlightjs-chapel

can we support syntax highlight for chapel now? Let me know if anything else is needed from my side

**Comment by ErikSchierboom** [comment]
Thanks, we'll look into it!

**Comment by lucaferranti** [comment]
@ErikSchierboom, @iHiD  it seems the syntax highlight works partially.

The code snippet in the about page is correctly highlighted

![Screenshot from 2024-05-04 16-12-50](https://github.com/exercism/chapel/assets/49938764/ecf0f3a3-1fc2-4e51-82ce-2edf215e8cc1)

and when solving exercises the tests on the right side are also correctly highlighted

![Screenshot from 2024-05-04 16-09-57](https://github.com/exercism/chapel/assets/49938764/feff3d51-e10f-42c6-b23d-daf99b16c08f)

However, it seems that syntax highlight does not work in the text editor itself

![Screenshot from 2024-05-04 16-12-04](https://github.com/exercism/chapel/assets/49938764/73d63669-64fe-489b-a8b3-5cff1a80d03b)

could you take a look?

**Comment by ErikSchierboom** [comment]
That's because the online editor uses CodeMirror, so you'd have to create a CodeMirror language plugin for the syntax highlighting to work in the online editor.

**Comment by lucaferranti** [comment]
Oh maan, I didn't know that.

Do all other tracks have a CodeMirror plugin? If not, how do people find usability of the track without syntax highlight in the editor? Do you have any feedback on that?

**Comment by ErikSchierboom** [comment]
Many tracks have a CodeMirror plugin, yes, but not all. We don't have any feedback on how students perceive their learning experience without syntax highlighting.

**Comment by lucaferranti** [comment]
I'll close this and make a new issue to track the codemirror integration
